name: Build and deploy

on:
  push:
    branches:
      - main
      - ci-optimise
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run Gradle Release
        run: ./gradlew release
      - name: Upload tag number
        uses: actions/upload-artifact@v2
        with:
          name: tag
          path: tag.txt
      - name: Commit release changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "[ci skip] Bump version number"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set Environment
        run: |
          echo "TAG_NUMBER=$(cat tag.txt)" >> $GITHUB_ENV
          echo "RELEASE=$(cat release.txt)" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: /build/libs/${{ env.TAG_NUMBER }}.jar
      - name: Build and push release
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ${{ env.TAG_NUMBER }}.jar
          push: true
          tags: mbruty/swgoh-api:${{ env.RELEASE }}
  container:
    name: Build Container
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download tag
        uses: actions/download-artifact@v2
        with:
          name: tag
      - name: Set Environment
        run: echo "TAG_NUMBER=$(cat tag.txt)" >> $GITHUB_ENV
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: jar
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: ${{ env.TAG_NUMBER }}.jar
          tags: |
            docker.pkg.github.com/${{ github.repository }}/api-image:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/api-image:${{ env.TAG_NUMBER }}
            docker.pkg.github.com/${{ github.repository }}/api-image:${{ env.RELEASE }}

  deploy:
    name: Deploy container
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SSH pipeline
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          connect_timeout: 10s
          script: |
            docker container stop API
            docker container rm API
            docker pull mbruty/swgoh-api:latest
            docker run -d -p 80:8080 --name API mbruty/swgoh-api
  tag:
    name: Create a GitHub tag
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download tag
        uses: actions/download-artifact@v2
        with:
          name: tag
      - name: Set Environment
        run: echo "TAG_NUMBER=$(cat tag.txt)" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.TAG_NUMBER }}',
              sha: context.sha
            })
  deploy-snapshot:
    name: Deploy snapshot container
    needs: build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: SSH pipeline
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          connect_timeout: 10s
          script: |
            docker container stop API
            docker container rm API
            docker pull mbruty/swgoh-api:snapshot
            docker run -d -p 8080:8080 --name API mbruty/swgoh-api
